baselineName:
  - name: "Master-Slave mode"
    name-zh: "主从模式"
  - name: "Master-Slave mode A-A"
    name-zh: "主从模式-双活"
  - name: "Proxy"
    name-zh: "代理模式"
  - name: "Proxy mode A-A"
    name-zh: "代理模式-双活"
  - name: "Standard"
    name-zh: "标准版"
  - name: "HighAvailability"
    name-zh: "高可用版"
description:
  - name: "MySQL DataBase"
    name-zh: "MySQL 数据库"
  - name: "Master-Slave Mode Baseline, incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "主从模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."

  - name: "High Availability/HA Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "高可用版基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
  - name: "Standard Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "标准版基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
  - name: "Proxy Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "代理模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."


  - name: "Please enter a custom quota, the unit is `Core`"
    name-zh: "请输入自定义配额,单位为Core"
  - name: "Please enter a custom quota, the unit is `Gi`"
    name-zh: "请输入自定义配额,单位为Gi"
  - name: "Number of nodes in the MySQL cluster, with a range of 2 to 5 nodes"
    name-zh: "MySQL集群的节点数量，节点数范围2至5"
  - name: "Number of nodes in the MySQL cluster is 2 or 4"
    name-zh: "MySQL集群的节点数量，节点数为2或4"
  - name: "The number of nodes in a MySQL cluster is recommended to be at least 2 to ensure high availability."
    name-zh: "MySQL集群的节点数量，建议至少2个以保证高可用"
  - name: "Please enter the storage size"
    name-zh: "请输入存储大小"
  - name: "Please select storage"
    name-zh: "请选择存储"
  - name: "Please enter a password consisting of English letters, numbers, or the special characters \"/, ~, %, _, .\""
    name-zh: "请输入由英文字母、数字或特殊字符“/、~、%、_、.”组成的密码信息"
  - name: "Minimum storage size is 5"
    name-zh: "存储大小最低为5"

placeholder:
  - name: "Please enter a custom quota, the unit is `Gi`"
    name-zh: "请输入自定义配额,单位为Gi"
  - name: "Please enter a custom quota, the unit is `Core`"
    name-zh: "请输入自定义配额,单位为Core"
  - name: "Please enter the storage size"
    name-zh: "请输入存储大小"
  - name: "Please select storage"
    name-zh: "请选择存储"
  - name: "Please enter the number of instances"
    name-zh: "请输入实例数"
  - name: "Enter your admin password"
    name-zh: "输入管理员账户密码"

label:
  - name: "AdminPassword"
    name-zh: "管理员账号密码"
  - name: "Memory"
    name-zh: "内存"
  - name: "Replicas"
    name-zh: "实例数"
  - name: "Version"
    name-zh: "版本"

  - name: "StorageSize"
    name-zh: "存储大小"

  - name: "StorageClass"
    name-zh: "存储类"
  - name: "Turn off automatic switching?"
    name-zh: "是否关闭自动切换"
  - name: "Automatic switch"
    name-zh: "自动切换"

  - name: "CharacterSet"
    name-zh: "字符集"
  - name: "Collation Server"
    name-zh: "语言环境"


actionAliasName:
  - name: "MasterSlaveSwitchover"
    name-zh: "主从切换"
  - name: "Automatic switch"
    name-zh: "自动切换"
  - name: "Middleware Restart"
    name-zh: "服务重启"

