mainVersionGroups:
  "8.4.x":
    - "8.4.3"
  "8.0.x":
    - "8.0.39"
    - "8.0.45"

crossUpgradeRules:
  "8.4.x":
    - "8.4.x"
  "8.0.x":
    - "8.0.x"
crossDowngradeRules:
  "8.4.x": []
  "8.0.x": []