apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: mysql-restart
spec:
  baselineType: "NormalAction"
  actionType: "restart"
  necessary:
    namespace: "string"
    middlewareName: "string"
  steps:
    - name: isProxy
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - "kubectl"
          - "get"
          - "mid"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "{{ .Globe.MiddlewareName }}"
          - "-o"
          - "jsonpath='{.spec.proxy}'"
          - "|"
          - "awk"
          - '''/enable/ {found=1; exit} END {if (found) print "proxy"; else print "noproxy"}'''
    - name: restart
      cmd:
        command:
          - "kubectl"
          - "patch"
          - "MysqlCluster"
          - "{{ .Globe.MiddlewareName }}"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "--type=merge"
          - "-p"
          - '''{"metadata":{"annotations":{"middleware.maintenance.lock":"graceful-restart"{{ if eq .Step.isProxy.output "proxy" }},"middleware.maintenance.component":"proxysql"{{ end }}}}}'''
