apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: mysql-connection-credential
spec:
  template: |
    apiVersion: v1
    stringData:
      endpoint: {{ .Globe.Name }}.{{ .Globe.Namespace }}.svc
      port: "{{ .Values.args.server_port }}"
      username: root
      password: "{{ .Values.args.root_password }}"
    kind: Secret
    metadata:
      name: {{ .Globe.Name }}-credential
      namespace: {{ .Globe.Namespace }}
    type: Opaque