# Copyright 2025 OpenSaola Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: mysql-failover
  annotations:
    alias: "MasterSlaveSwitchover"
spec:
  baselineType: "OpsAction"
  actionType: "failover"
  necessary: {}
  steps:
    - name: getSyncSlave
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - |
            kubectl get mid {{ .Globe.MiddlewareName }} -n {{ .Necessary.namespace }} -o jsonpath='{.status.customResources.include.pods[?(@.type=="SyncSlave")].name}'
    - name: getVersion
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - |
            kubectl get mid {{ .Globe.MiddlewareName }} -n {{ .Necessary.namespace }} -o jsonpath='{.spec.necessary.version}'
    - name: failover
      cmd:
        command:
          - |
            kubectl exec {{ .Step.getSyncSlave.output }} -n {{ .Globe.Namespace }} -c mysql -- bash -c "curl -X POST -w '''\n%{http_code}\n''' http://mysql-operator.middleware-operator:8080/failover -d '''{\"candidate\": \"{{ .Step.getSyncSlave.output }}\",\"namespace\":\"{{ .Necessary.namespace }}\",\"name\":\"{{ .Globe.MiddlewareName }}\"}'''"