apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: mysql-failover
  annotations:
    alias: "MasterSlaveSwitchover"
spec:
  baselineType: "OpsAction"
  actionType: "failover"
  necessary: {}
  steps:
    - name: getSyncSlave
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - |
            kubectl get mid {{ .Globe.MiddlewareName }} -n {{ .Necessary.namespace }} -o jsonpath='{.status.customResources.include.pods[?(@.type=="SyncSlave")].name}'
    - name: getVersion
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - |
            kubectl get mid {{ .Globe.MiddlewareName }} -n {{ .Necessary.namespace }} -o jsonpath='{.spec.necessary.version}'
    - name: failover
      cmd:
        command:
          - |
            kubectl exec {{ .Step.getSyncSlave.output }} -n {{ .Globe.Namespace }} -c mysql -- bash -c "curl -X POST -w '''\n%{http_code}\n''' http://mysql-operator.middleware-operator:8080/failover -d '''{\"candidate\": \"{{ .Step.getSyncSlave.output }}\",\"namespace\":\"{{ .Necessary.namespace }}\",\"name\":\"{{ .Globe.MiddlewareName }}\"}'''"