apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: mysql-passive-switch
  annotations:
    alias: "Automatic switch"
spec:
  baselineType: "OpsAction"
  actionType: "passive-switch"
  necessary:
    passiveSwitched: '{"type":"boolean","label":"Automatic switch","required":true,"default":false,"visible":true}'
  steps:
    - name: passive-switch
      cmd:
        command:
          - "kubectl"
          - "patch"
          - "mid"
          - "{{ .Globe.MiddlewareName }}"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "--type='json'"
          - '-p=''[{"op": "add", "path": "/spec/parameters", "value": {}},{"op": "replace", "path": "/spec/parameters/passiveSwitched", "value": {{ .Necessary.passiveSwitched }} }]'''
