apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: pre-mysql-logging-rule
spec:
  baselineType: "PreAction"
  actionType: "pre-logging"
  necessary:
    fileLogging: "bool"
    stdoutLogging: "bool"
    auditLogging: "bool"
    slowqueryLogging: "bool"
  steps:
    - name: logging
      type: "KubectlEdit" # KubectlGet、KubectlEdit、KubectlExec、Exec、HTTP
      cue: |
        output: {
          spec: parameters.spec
        }
        parameters: {
          spec: {
            parameters: {
              statefulset: {
                env: []
              }
            }
            configurations: [
              {
                name: "mysql-logcollectionrule"
                values: {
                  logging: {
                    fileLogging: {{ if hasKey .Necessary "fileLogging" }}{{ .Necessary.fileLogging }}{{ else }}false{{ end }}
                    stdoutLogging: {{ if hasKey .Necessary "stdoutLogging" }}{{ .Necessary.stdoutLogging }}{{ else }}false{{ end }}
                    auditLogging: {{ if hasKey .Necessary "auditLogging" }}{{ .Necessary.auditLogging }}{{ else }}false{{ end }}
                    slowqueryLogging: {{ if hasKey .Necessary "slowqueryLogging" }}{{ .Necessary.slowqueryLogging }}{{ else }}false{{ end }}
                  }
                }
              },
              {
                name: "mysql-config"
                values: {
                  features: {
                    auditLog: {
                      enabled: {{ if hasKey .Necessary "auditLogging" }}{{ .Necessary.auditLogging }}{{ else }}false{{ end }}
                    }
                  }
                }
              },
            ]
          }
          resource: {
            apiversion: "middleware.cn/v1"
            kind: "Middleware"
            name: "{{ .Globe.Name }}"
            namespace: "{{ .Globe.Namespace }}"
          }
        }
