# Copyright 2025 OpenSaola Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: mysql-restart
  annotations:
    alias: "Middleware Restart"
spec:
  baselineType: "OpsAction"
  actionType: "restart"
  necessary:
    namespace: "string"
    middlewareName: "string"
  steps:
    - name: isProxy
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - "kubectl"
          - "get"
          - "MysqlCluster"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "{{ .Globe.MiddlewareName }}"
          - "-o"
          - "jsonpath='{.spec.proxy}'"
          - "|"
          - "awk"
          - '''/"enable":true/ {found=1; exit} END {if (found) print "proxy"; else print "noproxy"}'''
    - name: restart
      cmd:
        command:
          - "kubectl"
          - "patch"
          - "MysqlCluster"
          - "{{ .Globe.MiddlewareName }}"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "--type=merge"
          - "-p"
          - '''{"metadata":{"annotations":{"middleware.maintenance.lock":"graceful-restart"}}}'''
    - name: waitForReady
      output:
        type: "string"
        expose: false
      cmd:
        command:
          - '{{ if eq .Step.isProxy.output "proxy" }}i=0; while [ $i -lt 60 ] && kubectl get MysqlCluster -n {{ .Globe.Namespace }} {{ .Globe.MiddlewareName }} -o yaml 2>/dev/null | grep -q "middleware.maintenance.lock:"; do i=$((i+1)); echo "第 $i 次检查，维护锁存在"; sleep 10; done; echo "完成"{{ else }}echo 1{{ end }}'
    - name: restartPredixy
      cmd:
        command:
          - '{{ if eq .Step.isProxy.output "proxy" }}kubectl annotate MysqlCluster -n {{ .Globe.Namespace }} {{ .Globe.MiddlewareName }} middleware.maintenance.lock=graceful-restart middleware.maintenance.component=proxysql --overwrite=true{{ else }}echo 1{{ end }}'
