apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: mysql-restart
  annotations:
    alias: "Middleware Restart"
spec:
  baselineType: "OpsAction"
  actionType: "restart"
  necessary:
    namespace: "string"
    middlewareName: "string"
  steps:
    - name: isProxy
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - "kubectl"
          - "get"
          - "mid"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "{{ .Globe.MiddlewareName }}"
          - "-o"
          - "jsonpath='{.spec.proxy}'"
          - "|"
          - "awk"
          - '''/enable/ {found=1; exit} END {if (found) print "proxy"; else print "noproxy"}'''
    - name: restart
      cmd:
        command:
          - "kubectl"
          - "patch"
          - "MysqlCluster"
          - "{{ .Globe.MiddlewareName }}"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "--type=merge"
          - "-p"
          - '''{"metadata":{"annotations":{"middleware.maintenance.lock":"graceful-restart"}}}'''
    - name: waitForReady
      output:
        type: "string"
        expose: false
      cmd:
        command:
          - '{{ if eq .Step.isProxy.output "proxy" }}i=0; while [ $i -lt 60 ] && kubectl get MysqlCluster -n {{ .Globe.Namespace }} {{ .Globe.MiddlewareName }} -o yaml 2>/dev/null | grep -q "middleware.maintenance.lock:"; do i=$((i+1)); echo "第 $i 次检查，维护锁存在"; sleep 10; done; echo "完成"{{ else }}echo 1{{ end }}'
    - name: restartPredixy
      cmd:
        command:
          - '{{ if eq .Step.isProxy.output "proxy" }}kubectl annotate MysqlCluster -n {{ .Globe.Namespace }} {{ .Globe.MiddlewareName }} middleware.maintenance.lock=graceful-restart middleware.maintenance.component=proxysql --overwrite=true{{ else }}echo 1{{ end }}'
